### ISSUE TITLE
Can't run example/naive-example locally

### ISSUE THREAD

**Issue by marekruttner** [mobile-blockly/react-blockly#12]
Hello, I wanted to run your example of react-native app on my machine and afteter runnig `yarn start` and `w` for running on web I ended with this error: 

`ERROR in ./src/App.js:4
Module not found: Can't resolve '@react-blockly/native'
  2 | import { Platform, StyleSheet } from 'react-native';
  3 |
> 4 | import { BlocklyEditor } from '@react-blockly/native';
  5 | import { SafeAreaView } from 'react-native-safe-area-context';
  6 |
  7 | import { ComponentWithHook } from './ComponentWithHook';

ERROR in ./src/ComponentWithHook.js:4
Module not found: Can't resolve '@react-blockly/core'
  2 | import { Platform } from 'react-native';
  3 |
> 4 | import { useBlocklyNativeEditor } from '@react-blockly/core';
  5 | import { WebView } from 'react-native-webview';
  6 |
  7 | import ConfigFiles from './content';

web compiled with 2 errors`

I tried to install @react-blockly/native and @react-blockly/core but after that it doesnt work. Could you provide more information how to run this project locally and some inofrmation about your development enviroment?

**Comment by SerSerch** [comment]
@marekruttner Hello!
if you have cloned the repository, go to root the repository and run
```
yarn install
yarn native start
```

in the example, expo is configured for a monorepository. try creating a new expo project.
https://docs.expo.dev/tutorial/create-your-first-app/
While I was writing, I tried to create a new expo project.
But WebView doesn't work for some reason. I will try to find out the reason.

**Comment by SerSerch** [comment]
@marekruttner Hello!
I created a new repository for testing. try this
https://github.com/react-blockly/expo-blockly-example
